### ISSUE TITLE
Global variable declarations incorrect

### ISSUE THREAD

**Issue by kquick** [GaloisInc/llvm-pretty#123] opened 2023-08-07 23:38 UTC
When using clang for any LLVM version starting with 11, the pretty-printed output for global variable declarations is incorrect and fails `llvm-as` assembly.

**Comment by kquick** [comment] 2023-08-08 00:24
For more information, see https://github.com/GaloisInc/llvm-pretty-bc-parser/pull/243

**Comment by RyanGlScott** [comment] 2023-09-26 10:27
Per https://github.com/elliottt/llvm-pretty/issues/128#issuecomment-1732689095, closing as a duplicate of #128.

**Closed as completed by RyanGlScott** 2023-09-26 10:27 UTC
